### ISSUE TITLE
Give Cross-Certified User Admin Access to Server

### ISSUE THREAD

**Issue by JoelProminic** [DominoVagrant/demo#3]
I can access the `demo/DEMO` server with my local Notes client after cross-certifying my Notes ID, but I don't have the admin rights I need to create/import agents and change the server settings.

We discussed this with @JustinProminic in the meeting today, and we would like to give the cross-certified user full access to the Domino server.  We can do this in in a couple stages.

Update setup.json to create a special group for cross-certified users and give it access:
- Group Name:  AutomaticallyCrossCertifiedUsers
- Update the server document to give AutomaticallyCrossCertifiedUsers the same access as LocalDomainAdmins.  We can tweak these settings later if needed.

When running CrossCertifyNotesID (Java), add the corresponding user to the AutomaticallyCrossCertifiedUsers group.  To get the user ID, find the newly created cross-certificate document in the `($CrossCertByName)` view in names.nsf.  In the long term, we may want to support multiple cross-certified IDs, so we may need a better solution for this.

**Comment by JoelProminic** [comment]
@dpastov updated setup.json to create the AutomaticallyCrossCertifiedUsers group and update the server document.

I updated CrossCertifiyNotesID to get the user name for the ID with the logic described above and add it to the AutomaticallyCrossCertifiedUsers groups.  

However, I'm still seeing that my cross-certified Notes ID doesn't have sufficient access to import the agents.  It seems like it is not recognized as part of the group.  I'll continue to debug this.

**Comment by JoelProminic** [comment]
I updated CrossCertifyNotesID to update the server document as well, to add explicit entries for the cross-certified user to the security fields:


```
			updateServerSecurityField(serverDoc, "FullAdmin", username);
			updateServerSecurityField(serverDoc, "CreateAccess", username);
			updateServerSecurityField(serverDoc, "ReplicaAccess", username);
			updateServerSecurityField(serverDoc, "UnrestrictedList", username);
			updateServerSecurityField(serverDoc, "OnBehalfOfInvokerLst", username);
			updateServerSecurityField(serverDoc, "LibsLst", username);
			updateServerSecurityField(serverDoc, "RestrictedList", username);
```

I couldn't run `computeWithForm against the server document because of this error.  For now, I skipped this step:

    Adding user '-snip-' to server document as authorized user.
    Using default notesID path.
    [018455:000002-00007FCD65B93700] ECL Alert Result: Code signed by Domino Template Development/Domino was prevented from executing with the right: Access to current database.NotesException: Operation aborted at your request
            at lotus.domino.local.Document.NcomputeWithForm(Native Method)
            at lotus.domino.local.Document.computeWithForm(Unknown Source)
            at net.prominic.domino.vagrant.CrossCertifyNotesID.addUserAsServerAdmin(CrossCertifyNotesID.java:381)
            at net.prominic.domino.vagrant.CrossCertifyNotesID.main(CrossCertifyNotesID.java:68)

I also added a command to the Vagrantfile to restart the server once the server document is updated.  For future reference, use `screen -X stuff "<command>^M"` to send a Domino command to the running Domino server.  This needs to run as `vagrant` or the screen will not be found.

    sudo su -c 'screen -X stuff "restart server^M"' - vagrant


Unfortunately, this is still not resolving the problems.  I did get the permissions working during my testing, but it did not work after running a fresh `vagrant up`.  I tried a `vagrant reload` as well to confirm the server fully restarted.  

The lack of `computeWithForm` seems like an obvious target for further investigation.  I'm thinking about whether I can run a separate command using the JSON syntax.

UPDATE:  I opened and saved the server document as the `Demo Admin/DEMO` user to trigger the computeWithForm, and this did not resolve the agent errors.

**Comment by JoelProminic** [comment]
After revisiting the deploy_database.sh script, I found that `-Default-` did not have permissions to create agents, which explains the DXL Importer error (this would not be a problem if the group were working properly).

I also tried updating the permissions for `Anonymous` to `Author` to resolve the runtime permission errors - I have seen this before for DXL Importer.   This worked in my initial test, but `Author` access seems too high for this database - I'll experiment with lowering this.

These updates resolved the agent errors I have been fighting recently, but I don't think it explains all of the strange behavior I have been seeing.   I'll do more testing with this.

**Comment by JoelProminic** [comment]
After some testing, I was able to reduce the permissions for Anonymous to ["depositor" with isPublicReader and isPublicWriter](https://github.com/DominoVagrant/demo/blob/5e577c387ee86660ea7f971f18aa86eee573402e/dist-support/rest_scripts/deploy_database.sh#L64-L70).

I tried removing the [server document update](https://github.com/DominoVagrant/demo/blob/5e577c387ee86660ea7f971f18aa86eee573402e/src/main/java/net/prominic/domino/vagrant/CrossCertifyNotesID.java#L68-L69) for `CrossCertifyNotesID`, but I found that this was still necessary.

The permissions are working reliably in my tests now.
